import React from 'react'

import './style.css'

const TermsOfService = () => (
   <div className='Term'>
     <h3>Terms of Service</h3>
     <p>The following terms and conditions ("Terms") govern all use of the Timeline.ink website and all content, services, and products available at or through the website, including, but not limited to, Timeline.ink("Timeline.ink"), and Timeline.ink Premium ("Timeline.ink"), (taken together, our "Services"). Our Services are offered subject to your acceptance without modification of all of the terms and conditions contained herein and all other operating rules, policies (including, without limitation, Timeline.ink Privacy Policy) and procedures that may be published from time to time. You agree that we may automatically upgrade our Services, and these Terms will apply to any upgrades.</p>
     <p>Please read this Agreement carefully before accessing or using our Services. By accessing or using any part of our Services, you agree to become bound by the Terms of this Agreement. If you do not agree to all the Terms of this Agreement, then you may not access or use any of our Services. If these Terms are considered an offer by Timeline.ink, acceptance is expressly limited to these Terms.</p>
     <p>Our Services are not directed to children younger than 13, and access and use of our Services is only offered to users 13 years of age or older. If you are under 13 years old, please do not to use our Services. Any person who uses or registers as a user or provides their personal information to our Services represents that they are 13 years of age or older.</p>
     <p>Use of our Services may or may not require a Timeline.ink account. You agree to provide us with complete and accurate information when you register for an account. You will be responsible and liable for any activity that occurs under your account. You are responsible for keeping your password secure. If you use our Services without an account, you are responsible for keeping the timeline URLs we generated for you secure.</p>

     <h4>1. Timeline.ink</h4>
     <ul>
       <li><b>Your Timeline.ink Timeline and Account.</b> If you create a timeline on Timeline.ink you are responsible for maintaining the security of your timeline and account, and you are fully responsible for all activities that occur under the timeline, account and any other actions taken in connection with the timeline and account. If you use our Services without an account, there is no way for Timeline.ink to identify you as the owner of the timeline, you are fully responsible for keeping the timeline URLs secure and only known to yourself. You must immediately notify Timeline.ink of any unauthorized uses of your account, or any other breaches of security. Timeline.ink will not be liable for any acts or omissions by you, including any damages of any kind incurred as a result of such acts or omissions.</li>
       <li><b>Responsibility of Contributors.</b> If you operate a timeline, post material to Timeline.ink, post links on Timeline.ink, or otherwise make (or allow any third party to make) material available (any such material, "Content"), you are entirely responsible for the content of, and any harm resulting from, that Content or your conduct. That is the case regardless of what form the Content takes, which includes, but is not limited to text, photo, video, audio, or code. By using Timeline.ink, you represent and warrant that your Content and conduct do not violate these Terms. If your timelines are shared to other Timeline.ink users, you give other Timeline.ink users permission to share, modify, delete your Content on the timelines, add their own Content to it, and recreate a new timeline based on yours. If you delete Content, Timeline.ink will use reasonable efforts to remove it from Timeline.ink, but you acknowledge that timelines created based on your original ones will not be removed, and caching or references to the Content may not be made immediately unavailable as well. Without limiting any of those representations or warranties, Timeline.ink has the right (though not the obligation) to, in Timeline.ink's sole discretion, (i) reclaim your username or timeline's URL due to prolonged inactivity, (ii) refuse or remove any content that, in Timeline.ink's reasonable opinion, violates any Timeline.ink policy or is in any way harmful or objectionable, or (iii) terminate or deny access to and use of Timeline.ink to any individual or entity for any reason. Timeline.ink will have no obligation to provide a refund of any amounts previously paid.</li>
       <li><b>Web Traffic.</b> We may use third party services, including but not limited to Google Analytics, comScore, to measure Timeline.ink's audience and usage. By hosting your timeline on Timeline.ink, you agree to assign the traffic relating to your timeline to Timeline.ink and authorize us to sign a Traffic Assignment Letter on your behalf for comScore audience measurement reports. Your timeline's traffic will be included under Timeline.ink. You understand that your timeline will not receive credit for traffic in these reports, and you must not assign your timeline's traffic to any other party.</li>
     </ul>

     <h4>2. Responsibility of Visitors.</h4>
     <p>Timeline.ink has not reviewed, and cannot review, all of the material, including computer software, posted to our Services, and cannot therefore be responsible for that material’s content, use or effects. By operating our Services, Timeline.ink does not represent or imply that it endorses the material there posted, or that it believes such material to be accurate, useful, or non-harmful. You are responsible for taking precautions as necessary to protect yourself and your computer systems from viruses, worms, Trojan horses, and other harmful or destructive content. Our Services may contain content that is offensive, indecent, or otherwise objectionable, as well as content containing technical inaccuracies, typographical mistakes, and other errors. Our Services may also contain material that violates the privacy or publicity rights, or infringes the intellectual property and other proprietary rights, of third parties, or the downloading, copying or use of which is subject to additional terms and conditions, stated or unstated. Timeline.ink disclaims any responsibility for any harm resulting from the use by visitors of our Services, or from any downloading by those visitors of content there posted.</p>

     <h4>3. Content Posted on Other Websites.</h4>
     <p>We have not reviewed, and cannot review, all of the material, including computer software, made available through the websites and webpages to which Timeline.ink links, and that link to Timeline.ink. Timeline.ink does not have any control over those non-Timeline.ink websites, and is not responsible for their contents or their use. By linking to a non-Timeline.ink website, Timeline.ink does not represent or imply that it endorses such website. You are responsible for taking precautions as necessary to protect yourself and your computer systems from viruses, worms, Trojan horses, and other harmful or destructive content. Timeline.ink disclaims any responsibility for any harm resulting from your use of non-Timeline.ink websites and webpages.</p>

     <h4>4. Third Party Services.</h4>
     <p>You may enable services, products, software (like themes or plugins), or applications developed by a third party or yourself ("Third Party Services") on your site.</p>
     <p>If you use any Third Party Services, you understand that:</p>
     <ul>
       <li>Third Party Services are not vetted, endorsed, or controlled by Timeline.ink.</li>
       <li>Any use of a Third Party Service is at your own risk, and we shall not be responsible or liable to anyone for Third Party Services.</li>
       <li>Your use is solely between you and the respective third party ("Third Party") and will be governed by the Third Party’s terms and policies. It is your responsibility to review the Third Party’s terms and policies before using a Third Party Service.</li>
       <li>Some Third Party Services may request or require access to your (yours, your visitors’, or customers’) data. If you grant access, your data will handled in accordance with the Third Party’s privacy policy and practices. We do not have control over how a Third Party Service may use your data. You should carefully review Third Party Services’ data collection, retention, and use policies and practices before enabling Third Party Services.</li>
       <li>Third Party Services may not work appropriately with your timeline, and we may not be able to provide support for issues caused by any Third Party Services.</li>
       <li>If you have questions or concerns about how a Third Party Service operates, or need support, please contact the Third Party directly.</li>
     </ul>
     <p>In rare cases, we may at our discretion, suspend, disable, or remove Third Party Services from your account or timelines.</p>

     <h4>5. Copyright Infringement.</h4>
     <p>As Timeline.ink asks others to respect its intellectual property rights, it respects the intellectual property rights of others. If you believe that material located on or linked to by Timeline.ink violates your copyright, you are encouraged to notify Timeline.ink. Timeline.ink will respond to all such notices, including as required or appropriate by removing the infringing material or disabling all links to the infringing material. Timeline.ink will terminate a visitor’s access to and use of the timeline if, under appropriate circumstances, the visitor is determined to be a repeat infringer of the copyrights or other intellectual property rights of Timeline.ink or others. In the case of such termination, Timeline.ink will have no obligation to provide a refund of any amounts previously paid to Timeline.ink.</p>

     <h4>6. Intellectual Property.</h4>
     <p>This Agreement does not transfer from Timeline.ink to you any Timeline.ink or third party intellectual property, and all right, title, and interest in and to such property will remain (as between the parties) solely with Timeline.ink. Timeline.ink, the Timeline.ink logo, and all other trademarks, service marks, graphics and logos used in connection with Timeline.ink or our Services, are trademarks or registered trademarks of Timeline.ink or Timeline.ink's licensors. Other trademarks, service marks, graphics and logos used in connection with our Services may be the trademarks of other third parties. Your use of our Services grants you no right or license to reproduce or otherwise use any Timeline.ink or third-party trademarks.</p>

     <h4>7. Changes.</h4>
     <p>We are constantly updating our Services, and that means sometimes we have to change the legal terms under which our Services are offered. If we make changes that are material, we will let you know by prompting messages at the top of web pages, or by sending you an email if you have registered with your email or other communication before the changes take effect. The notice will designate a reasonable period of time after which the new terms will take effect. If you disagree with our changes, then you should stop using our Services within the designated notice period. Your continued use of our Services will be subject to the new terms. However, any dispute that arose before the changes shall be governed by the Terms (including the binding individual arbitration clause) that were in place when the dispute arose.</p>

     <h4>8. Termination.</h4>
     <p>Timeline.ink may terminate your access to all or any part of our Services at any time, with or without cause, with or without notice, effective immediately. If you wish to terminate this Agreement or your Timeline.ink account (if you have one), you may simply discontinue using our Services. All provisions of this Agreement which by their nature should survive termination shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, indemnity and limitations of liability.</p>

     <h4>9. Disclaimer of Warranties.</h4>
     <p>Our Services are provided "as is."" Timeline.ink and its suppliers and licensors hereby disclaim all warranties of any kind, express or implied, including, without limitation, the warranties of merchantability, fitness for a particular purpose and non-infringement. Neither Timeline.ink nor its suppliers and licensors, makes any warranty that our Services will be error free or that access thereto will be continuous or uninterrupted. You understand that you download from, or otherwise obtain content or services through, our Services at your own discretion and risk.</p>

     <h4>10. Jurisdiction and Applicable Law.</h4>
     <p>Except to the extent applicable law, if any, provides otherwise, this Agreement, any access to or use of our Services will be governed by the laws of New Zealand, excluding its conflict of law provisions, and the proper venue for any disputes arising out of or relating to any of the same will be New Zealand.</p>

     <h4>11. Limitation of Liability.</h4>
     <p>In no event will Timeline.ink, or its suppliers or licensors, be liable with respect to any subject matter of this Agreement under any contract, negligence, strict liability or other legal or equitable theory for: (i) any special, incidental or consequential damages; (ii) the cost of procurement for substitute products or services; (iii) for interruption of use or loss or corruption of data; or (iv) for any amounts that exceed the fees paid by you to Timeline.ink under this Agreement during the twelve (12) month period prior to the cause of action. Timeline.ink shall have no liability for any failure or delay due to matters beyond their reasonable control. The foregoing shall not apply to the extent prohibited by applicable law.</p>

     <h4>12. General Representation and Warranty.</h4>
     <p>You represent and warrant that (i) your use of our Services will be in strict accordance with the Timeline.ink Privacy Policy, with this Agreement, and with all applicable laws and regulations (including without limitation any local laws or regulations in your country, state, city, or other governmental area, regarding online conduct and acceptable content, and including all applicable laws regarding the transmission of technical data exported from the New Zealand or the country in which you reside) and (ii) your use of our Services will not infringe or misappropriate the intellectual property rights of any third party.</p>

     <h4>13. Indemnification.</h4>
     <p>You agree to indemnify and hold harmless Timeline.ink, its contractors, and its licensors, and their respective directors, officers, employees, and agents from and against any and all claims and expenses, including attorneys' fees, arising out of your use of our Services, including but not limited to your violation of this Agreement.</p>

     <h4>13. Translation.</h4>
     <p>These Terms of Service were originally written in English. We may translate these terms into other languages. In the event of a conflict between a translated version of these Terms of Service and the English version, the English version will control.</p>

     <h4>14. Miscellaneous.</h4>
     <p>This Agreement constitutes the entire agreement between Timeline.ink and you concerning the subject matter hereof, and they may only be modified by a written amendment signed by an authorized executive of Timeline.ink, or by the posting by Timeline.ink of a revised version.</p>
     <p>If any part of this Agreement is held invalid or unenforceable, that part will be construed to reflect the parties’ original intent, and the remaining portions will remain in full force and effect. A waiver by either party of any term or condition of this Agreement or any breach thereof, in any one instance, will not waive such term or condition or any subsequent breach thereof.</p>
     <p>You may assign your rights under this Agreement to any party that consents to, and agrees to be bound by, its terms and conditions; Timeline.ink may assign its rights under this Agreement without condition. This Agreement will be binding upon and will inure to the benefit of the parties, their successors and permitted assigns.</p>
   </div>
)

export default TermsOfService
